version: '3.3'
services:
  website:
    image: php:apache
    depends_on:
      - API
    ports:
      - "8084:80"
    volumes:
      - ./website:/var/www/html
    networks:
      - studentlist
    environment:
      - USERNAME=toto
      - PASSWORD=python
  API:
    image: pozos:latest
    #ports:
     # - "8085:5000"
    volumes:
       - ./simple_api/student_age.json:/data/student_age.json
    networks:
       - studentlist
    
  registry:
     image: registry:2
     container_name: registry
     ports:
       - "5000:5000"
     networks:
       - studentlist

  registry-ui:
     image: joxit/docker-registry-ui
     depends_on:
       - registry
     container_name: registry-ui
     ports:
       - "80:80"
     networks:
       - studentlist
     environment:
       - SINGLE_REGISTRY=true
       - REGISTRY_TITLE=Docker Registry UI
       - DELETE_IMAGES=true
       - SHOW_CONTENT_DIGEST=true
       - NGINX_PROXY_PASS_URL=http://registry:5000
       - SHOW_CATALOG_NB_TAGS=true
       - CATALOG_MIN_BRANCHES=1
       - CATALOG_MAX_BRANCHES=1
       - TAGLIST_PAGE_SIZE=100
       - REGISTRY_SECURED=false
       - CATALOG_ELEMENTS_LIMIT=1000
 
networks:
  studentlist:
