version: '3.3'
services:
  website:
    image: php:apache
    depends_on:
      - API
    ports:
      - "8084:80"
    volumes:
      - ./website:/var/www/html
    networks:
      - studentlist
    environment:
      - USERNAME=toto
      - PASSWORD=python
  API:
    image: pozos:latest
    #ports:
     # - "8085:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - studentlist
networks:
  studentlist:
